CREATE TABLE DIVIDEND(
        CODE VARCHAR(10) NOT NULL PRIMARY KEY,
        COMPANY VARCHAR(255) NOT NULL,
        SECTOR VARCHAR(255) NOT NULL,
        SECOND_SECTOR VARCHAR(255),
        STOCK_PRICE DECIMAL(10,2) NOT NULL,
        STOCK_TYPE VARCHAR(2) NOT NULL,
        VALUATION DECIMAL(10,2) NOT NULL,
        STOCK_AVAILABLE_AMOUNT DECIMAL(10) NOT NULL,
        AVG_21_NEGOCIATION DECIMAL(10,2) NOT NULL,
        DIVIDEND_PERIOD DECIMAL(2) NOT NULL,
        DIVIDEND_LAST_PRICE DECIMAL(10,2) NOT NULL,
        DIVIDEND_TOTAL_VALUE_SHARED DECIMAL(20,2) NOT NULL,
        NET_PROFIT DECIMAL(20) NOT NULL,
        DIVIDEND_YELD DECIMAL(10,2) NOT NULL,
        AVG_PAYOUT_12_MONTHS DECIMAL(10,2) NOT NULL,
        AVG_PAYOUT_5_YEARS DECIMAL(10,2) NOT NULL,
        MAJOR_SHARE_HOLDER VARCHAR(255) NOT NULL
)