DELIMITER //

CREATE PROCEDURE SP_INSERT_DIVIDEND 
	(
    IN CODE VARCHAR(10), 
    IN COMPANY VARCHAR(255), 
    IN SECTOR VARCHAR(255), 
    IN SECOND_SECTOR VARCHAR(255),
	IN STOCK_PRICE DECIMAL(10, 2),
	IN STOCK_TYPE VARCHAR(2),
	IN VALUATION DECIMAL(10, 2),
	IN STOCK_AVAILABLE_AMOUNT DECIMAL(10, 0),
	IN AVG_21_NEGOCIATION DECIMAL(10, 2),
	IN DIVIDEND_PERIOD DECIMAL(2, 0),
	IN DIVIDEND_LAST_PRICE DECIMAL(10, 2),
	IN DIVIDEND_TOTAL_VALUE_SHARED DECIMAL(20, 2),
	IN NET_PROFIT DECIMAL(20, 2),
	IN DIVIDEND_YELD DECIMAL(10, 2),
	IN AVG_PAYOUT_12_MONTHS DECIMAL(10, 2),
	IN AVG_PAYOUT_5_YEARS DECIMAL(10, 2),
	IN MAJOR_SHARE_HOLDER VARCHAR(255)
    )
BEGIN
	IF (SELECT COUNT(D.CODE) FROM SYS.DIVIDEND AS D WHERE D.CODE = CODE) = 0
		THEN
			INSERT INTO `sys`.`dividend`
			(
			`CODE`,
			`COMPANY`,
			`SECTOR`,
			`SECOND_SECTOR`,
			`STOCK_PRICE`,
			`STOCK_TYPE`,
			`VALUATION`,
			`STOCK_AVAILABLE_AMOUNT`,
			`AVG_21_NEGOCIATION`,
			`DIVIDEND_PERIOD`,
			`DIVIDEND_LAST_PRICE`,
			`DIVIDEND_TOTAL_VALUE_SHARED`,
			`NET_PROFIT`,
			`DIVIDEND_YELD`,
			`AVG_PAYOUT_12_MONTHS`,
			`AVG_PAYOUT_5_YEARS`,
			`MAJOR_SHARE_HOLDER`
			)
			VALUES
			(
			CODE,
			COMPANY,
			SECTOR,
			SECOND_SECTORSTOCK_PRICE,
			STOCK_TYPE,
			VALUATION,
			STOCK_AVAILABLE_AMOUNT,
			AVG_21_NEGOCIATION,
			DIVIDEND_PERIOD,
			DIVIDEND_LAST_PRICE,
			DIVIDEND_TOTAL_VALUE_SHARED,
			NET_PROFIT,
			DIVIDEND_YELD,
			AVG_PAYOUT_12_MONTHS,
			AVG_PAYOUT_5_YEARS,
			MAJOR_SHARE_HOLDER
			);
    ELSE
			UPDATE `sys`.`dividend`
				SET
					`CODE` = CODE,
					`COMPANY` = COMPANY,
					`SECTOR` = SECTOR,
					`SECOND_SECTOR` = SECOND_SECTOR,
					`STOCK_PRICE` = STOCK_PRICE,
					`STOCK_TYPE` = STOCK_TYPE,
					`VALUATION` = VALUATION,
					`STOCK_AVAILABLE_AMOUNT` = STOCK_AVAILABLE_AMOUNT,
					`AVG_21_NEGOCIATION` = AVG_21_NEGOCIATION,
					`DIVIDEND_PERIOD` = DIVIDEND_PERIOD,
					`DIVIDEND_LAST_PRICE` = DIVIDEND_LAST_PRICE,
					`DIVIDEND_TOTAL_VALUE_SHARED` = DIVIDEND_TOTAL_VALUE_SHARED,
					`NET_PROFIT` = NET_PROFIT,
					`DIVIDEND_YELD` = DIVIDEND_YELD,
					`AVG_PAYOUT_12_MONTHS` = AVG_PAYOUT_12_MONTHS,
					`AVG_PAYOUT_5_YEARS` = AVG_PAYOUT_5_YEARS,
					`MAJOR_SHARE_HOLDER` = MAJOR_SHARE_HOLDER
			WHERE SYS.DIVIDEND.CODE = CODE;
	END IF;
	COMMIT;
END //

DELIMITER ;