class BuyNHoldeModel:
    Code: ""
    Company: ""
    Sector: ""
    SecondSector: ""
    StockPrice: 0.00
    Type: ""
    StockAvailableAmount: 0
    Valuation: 0.00
    Equity: 0.00
    Avg21Negociation: 0
    DividendPeriod: 0
    DividendLastPrice: 0.00
    DividendTotalValueShared: 0.00
    NetProfit: 0.00
    DividendYeld: 0.00
    AvgPayout12Months: 0.00
    AvgPayout5Years: 0.00
    MajorShareholder: ""
    DetailsPage: ""
    ReturnOnEquity: 0.00
    GrossDebitOverEbitda: 0.00
    GrossDebitOverEbitda_5yrAvg: 0.00